apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
        - name: stress-container
          image: polinux/stress
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          command: ["stress"]
          args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "100M", "--timeout", "300s"]